name: Release

on:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: master
            label: latest
          - branch: develop
            label: latest-dev
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Mainsail ${{ matrix.branch }} branch
        id: repo
        run: |
          git config --global user.name 'username'
          git config --global user.email 'username@users.noreply.github.com'

          git clone -b ${{ matrix.branch }} --depth 1 https://github.com/mainsail-crew/mainsail

          MAINSAIL_SHA=$(git -C mainsail rev-parse HEAD)

          echo ::set-output name=mainsail_sha::${MAINSAIL_SHA}

      - name: Check if Docker image already exists
        id: check
        run: |
          BUILD_IMAGE=false

          docker manifest inspect ghcr.io/${{ github.repository }}:sha-${{ steps.repo.outputs.mainsail_sha }} > /dev/null || BUILD_IMAGE=true

          echo ::set-output name=build_image::${BUILD_IMAGE}

      - name: Setup Node
        if: ${{ steps.check.outputs.build_image == 'true' }}
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install Mainsail dependencies
        if: ${{ steps.check.outputs.build_image == 'true' }}
        run: |
          npm ci
        working-directory: ./mainsail

      - name: Build Mainsail
        if: ${{ steps.check.outputs.build_image == 'true' }}
        run: |
          npm run build
        working-directory: ./mainsail

      - name: Prepare GitHub metadata
        if: ${{ steps.check.outputs.build_image == 'true' }}
        id: github_meta
        run: |
          REPOSITORY_NAME=${GITHUB_REPOSITORY#*/}

          echo ::set-output name=repository_name::${REPOSITORY_NAME}

      - name: Prepare Docker image metadata
        if: ${{ steps.check.outputs.build_image == 'true' }}
        id: docker_meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ steps.github_meta.outputs.repository_name }}
            ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=sha-${{ steps.repo.outputs.mainsail_sha }}
            type=raw,value=${{ matrix.branch }}
            type=raw,value=${{ matrix.label }}

      - name: Set up QEMU
        if: ${{ steps.check.outputs.build_image == 'true' }}
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        if: ${{ steps.check.outputs.build_image == 'true' }}
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        if: ${{ steps.check.outputs.build_image == 'true' }}
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Log in to the Container registry
        if: ${{ steps.check.outputs.build_image == 'true' }}
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        if: ${{ steps.check.outputs.build_image == 'true' }}
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
