name: Release

on:
  push:
  schedule:
    - cron: "*/20 * * * *"
  workflow_dispatch:

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - branch: master
            label: latest
          - branch: develop
            label: latest-dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Clone Mainsail ${{ matrix.branch }} branch
        run: |
          git config --global user.name 'username'
          git config --global user.email 'username@users.noreply.github.com'

          git clone -b ${{ matrix.branch }} --depth 1 https://github.com/mainsail-crew/mainsail

      - name: Build Mainsail code
        id: build
        run: |
          npm ci --ignore-scripts --no-optional
          npm run build

          MAILSAIL_SHA=$(git rev-parse HEAD)

          echo ::set-output name=mailsail_sha::${MAILSAIL_SHA}
        working-directory: ./mainsail

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm/v6,linux/arm/v7,linux/arm64/v8,linux/ppc64le,linux/s390x
          push: true
          tags: |
            ei99070/docker-mainsail:${{ matrix.label }}
            ei99070/docker-mainsail:${{ steps.build.outputs.mailsail_sha }}
